export const COMPANIES = [
  { id: 1, company: 'Evogene Ltd.', sector: 'Basic Industries' },
  { id: 2, company: 'Huntsman Corporation', sector: 'Basic Industries' },
  {
    id: 3,
    company: 'China Southern Airlines Company Limited',
    sector: 'Transportation',
  },
  { id: 4, company: 'Arch Capital Group Ltd.', sector: 'Asset Management' },
  {
    id: 5,
    company: 'China Advanced Construction Materials Group, Inc.',
    sector: 'Basic Industries',
  },
  {
    id: 6,
    company: 'Cellectar Biosciences, Inc.',
    sector: 'Health Care',
  },
  {
    id: 7,
    company: 'Maui Land & Pineapple Company, Inc.',
    sector: 'Finance',
  },
  { id: 8, company: 'MYOS RENS Technology Inc.', sector: 'Health Care' },
  {
    id: 9,
    company: 'FelCor Lodging Trust Incorporated',
    sector: 'Consumer Services',
  },
  { id: 10, company: 'Entergy Texas Inc', sector: 'Public Utilities' },
  { id: 11, company: 'Koninklijke Philips N.V.', sector: 'Energy' },
  { id: 12, company: 'Wix.com Ltd.', sector: 'Technology' },
  { id: 13, company: 'Spok Holdings, Inc.', sector: 'Public Utilities' },
  { id: 14, company: 'The Bancorp, Inc.', sector: 'Finance' },
  { id: 15, company: 'First Trust', sector: 'Asset Management' },
  { id: 16, company: 'Square, Inc.', sector: 'Technology' },
  { id: 17, company: 'CenterState Banks, Inc.', sector: 'Finance' },
  {
    id: 18,
    company: 'VelocityShares 3x Inverse Silver ETN',
    sector: 'Finance',
  },
  {
    id: 19,
    company: 'Forest City Realty Trust, Inc.',
    sector: 'Asset Management',
  },
  {
    id: 20,
    company: 'FactSet Research Systems Inc.',
    sector: 'Technology',
  },
  {
    id: 21,
    company: 'Tootsie Roll Industries, Inc.',
    sector: 'Consumer Non-Durables',
  },
  {
    id: 22,
    company: 'Hormel Foods Corporation',
    sector: 'Consumer Non-Durables',
  },
  { id: 23, company: 'eHealth, Inc.', sector: 'Finance' },
  { id: 24, company: 'Aegion Corp', sector: 'Basic Industries' },
  {
    id: 25,
    company: 'Invesco Municipal Income Opportunities Trust',
    sector: 'Asset Management',
  },
  {
    id: 26,
    company: 'China Auto Logistics Inc.',
    sector: 'Consumer Services',
  },
  {
    id: 27,
    company: 'Atmos Energy Corporation',
    sector: 'Public Utilities',
  },
  {
    id: 28,
    company: 'root9B Holdings, Inc.',
    sector: 'Consumer Services',
  },
  {
    id: 29,
    company: 'Ampco-Pittsburgh Corporation',
    sector: 'Capital Goods',
  },
  {
    id: 30,
    company: 'Nuveen AMT-Free Municipal Value Fund',
    sector: 'Asset Management',
  },
];
